import type { Metadata } from "next";
import { Fraunces, Figtree, Geist } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/src/components/site/header/page";
import FooterPage from "@/src/components/site/footer/page";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const fraunces = Fraunces({ subsets: ["latin"], variable: "--font-fraunces", display: "swap" });
const figtree = Figtree({ subsets: ["latin"], variable: "--font-figtree", display: "swap" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fraunces.variable, figtree.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning >
        <HeaderPage />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
